version: '3.8' 
services:
  db:
    image: mysql:5.7
    container_name: ${db_host}
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${db_pass}'
      MYSQL_DATABASE: '${db_name}'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '${db_pass}'
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
    networks:
      - frontweb
  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    volumes:
      - ./redis_init/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - frontweb
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
  web:
    image: jviguerasfortinet/xpertsummit22:php-xs22
    container_name: frontweb
    restart: always
    environment:
      DBHOST: '${db_host}'
      DBUSER: 'root'
      DBNAME: '${db_name}'
      DBTABLE: '${db_table}'
      DBPORT: '${db_port}'
      DBPASS: '${db_pass}'
    depends_on:
      - db
    volumes:
      - ./web_init:/var/www
    stdin_open: true
    tty: true
    networks:
      - frontweb
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3306
      PMA_ABSOLUTE_URI: http://${lab_fqdn}/${random_url_db}/
    networks:
      - frontweb
  checkscript:
    image: jviguerasfortinet/hol-checkscript:v1
    container_name: checkscript
    restart: always
    environment:
      DBHOST: '${db_host}'
      DBUSER: 'root'
      DBNAME: '${db_name}'
      DBTABLE: '${db_table}'
      DBPORT: '${db_port}'
      DBPASS: '${db_pass}'
      APP_PORT: '${app_port}'
    depends_on:
      - db
    networks:
      - frontweb
  proxynginx:
    image: nginx:latest
    container_name: proxynginx
    restart: always
    volumes:
      - ./proxy_init/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./proxy_init/html/index.html:/usr/share/nginx/html/index.html
    ports:
      - '80:80'
    networks:
      - frontweb
volumes:
  db:
    driver: local
networks:
  frontweb:
    external: true