apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger-petstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swagger-petstore
  template:
    metadata:
      labels:
        app: swagger-petstore
    spec:
      containers:
      - name: swagger-petstore
        image: swaggerapi/petstore
        ports:
        - containerPort: 8080
        env:
        - name: SWAGGER_HOST
          value: ${swagger_host}
        - name: SWAGGER_BASE_PATH
          value: "/api"
        - name: SWAGGER_URL
          value: ${swagger_url}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvwa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dvwa
  template:
    metadata:
      labels:
        app: dvwa
    spec:
      containers:
      - name: dvwa
        image: vulnerables/web-dvwa
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: swagger-petstore
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: ${swagger_nodeport}
  selector:
    app: swagger-petstore
---
apiVersion: v1
kind: Service
metadata:
  name: dvwa
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: ${dvwa_nodeport}
  selector:
    app: dvwa